#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
plot_malicious_sensitivity.py

Compile and plot malicious-client sensitivity results.

Expected folder pattern generated by run_malicious_sensitivity.py:
out_root/attack_<attack_type>/ratio_<ratio>/method_<method>/all_trials_metrics.csv

Example:
python plot_malicious_sensitivity.py \
  --results_root ./results_malicious_sensitivity/physionet2012_signflip \
  --out_dir ./plots_malicious_sensitivity/physionet2012_signflip \
  --metric auc \
  --paper
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

METHOD_LABELS = {
    "adaptive": "Proposed",
    "proposed": "Proposed",
    "fedavg": "FedAvg",
    "fedprox": "FedProx",
    "fedsgd": "FedSGD",
    "krum": "Krum",
    "multikrum": "Multi-Krum",
    "multi_krum": "Multi-Krum",
    "median": "Median",
    "trimmed_mean": "Trimmed Mean",
    "bulyan": "Bulyan",
}

MARKERS = ["o", "s", "^", "D", "v", "P", "X", "*", "<", ">", "h", "8"]
LINESTYLES = ["-", "-", "-", "-", (0, (3, 1, 1, 1)), (0, (5, 2))]


def set_plot_style(paper: bool = False, font_size: int = 15) -> None:
    if paper:
        matplotlib.rcParams["pdf.fonttype"] = 42
        matplotlib.rcParams["ps.fonttype"] = 42
        matplotlib.rcParams["font.family"] = "Times New Roman"
    matplotlib.rcParams["axes.unicode_minus"] = False
    plt.rcParams.update({
        "font.size": font_size,
        "axes.labelsize": font_size,
        "xtick.labelsize": max(10, font_size - 2),
        "ytick.labelsize": max(10, font_size - 2),
        "legend.fontsize": max(9, font_size - 6),
        "lines.linewidth": 2.6,
    })


def savefig(path_base: Path, dpi: int = 350) -> None:
    path_base.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(path_base.with_suffix(".pdf"), bbox_inches="tight", dpi=dpi)
    plt.savefig(path_base.with_suffix(".png"), bbox_inches="tight", dpi=dpi)
    plt.close()


def infer_ratio_from_path(path: Path) -> Optional[float]:
    for part in path.parts:
        m = re.match(r"ratio_([0-9.]+)", part)
        if m:
            try:
                return float(m.group(1))
            except ValueError:
                pass
    return None


def infer_method_from_path(path: Path) -> Optional[str]:
    for part in path.parts:
        if part.startswith("method_"):
            return part.replace("method_", "")
    return None


def load_all_metrics(results_root: str) -> pd.DataFrame:
    root = Path(results_root)
    files = sorted(root.rglob("all_trials_metrics.csv"))
    if not files:
        raise FileNotFoundError(f"No all_trials_metrics.csv found under {root}")

    dfs = []
    for f in files:
        df = pd.read_csv(f)
        df["source_file"] = str(f)
        df["source_dir"] = str(f.parent)

        if "malicious_ratio" not in df.columns or df["malicious_ratio"].isna().all():
            ratio = infer_ratio_from_path(f)
            if ratio is not None:
                df["malicious_ratio"] = ratio

        if "method" not in df.columns or df["method"].isna().all():
            method = infer_method_from_path(f)
            if method is not None:
                df["method"] = method

        dfs.append(df)

    out = pd.concat(dfs, ignore_index=True)
    if "malicious_ratio" not in out.columns:
        raise ValueError("Could not find or infer malicious_ratio.")
    if "method" not in out.columns:
        raise ValueError("Could not find or infer method.")
    if "round" not in out.columns:
        raise ValueError("all_trials_metrics.csv must contain a 'round' column.")

    out["malicious_ratio"] = pd.to_numeric(out["malicious_ratio"], errors="coerce")
    out["method"] = out["method"].astype(str).str.lower()
    out["method_display"] = out["method"].map(METHOD_LABELS).fillna(out["method"].str.replace("_", " ").str.title())
    if "trial" not in out.columns:
        out["trial"] = 1
    return out


def final_metric_summary(df: pd.DataFrame, metric: str) -> pd.DataFrame:
    if metric not in df.columns:
        available = [c for c in ["acc", "auc", "f1", "recall", "precision", "loss"] if c in df.columns]
        raise ValueError(f"Metric {metric!r} not found. Available common metrics: {available}")

    group_cols = ["source_dir", "trial", "method", "method_display", "malicious_ratio"]
    final_parts = []
    for _, g in df.groupby(group_cols, dropna=False):
        final_parts.append(g[g["round"] == g["round"].max()])
    final = pd.concat(final_parts, ignore_index=True)

    summary = final.groupby(["method", "method_display", "malicious_ratio"], as_index=False)[metric].agg(["mean", "std"]).reset_index()
    summary = summary.rename(columns={"mean": f"{metric}_mean", "std": f"{metric}_std"})
    return summary.sort_values(["method", "malicious_ratio"])


def robustness_degradation(summary: pd.DataFrame, metric: str) -> pd.DataFrame:
    value_col = f"{metric}_mean"
    rows = []
    for _, g in summary.groupby("method"):
        g = g.sort_values("malicious_ratio")
        base_rows = g[np.isclose(g["malicious_ratio"], 0.0)]
        if len(base_rows) == 0:
            baseline = g[value_col].iloc[0]
            baseline_ratio = g["malicious_ratio"].iloc[0]
        else:
            baseline = base_rows[value_col].iloc[0]
            baseline_ratio = 0.0

        for _, row in g.iterrows():
            current = row[value_col]
            if metric.lower() == "loss":
                degradation = current - baseline
            else:
                degradation = baseline - current
            rows.append({
                "method": row["method"],
                "method_display": row["method_display"],
                "baseline_ratio": baseline_ratio,
                "malicious_ratio": row["malicious_ratio"],
                f"{metric}_baseline": baseline,
                f"{metric}_current": current,
                f"{metric}_degradation": degradation,
            })
    return pd.DataFrame(rows)


def plot_sensitivity(summary: pd.DataFrame, metric: str, out_dir: Path) -> None:
    value_col = f"{metric}_mean"
    err_col = f"{metric}_std"
    plt.figure(figsize=(8.2, 5.3))
    for i, (label, g) in enumerate(summary.groupby("method_display", sort=False)):
        g = g.sort_values("malicious_ratio")
        yerr = g[err_col].to_numpy() if err_col in g.columns else None
        plt.errorbar(
            g["malicious_ratio"] * 100.0,
            g[value_col],
            # yerr=yerr,
            label=label,
            marker=MARKERS[i % len(MARKERS)],
            # linestyle=LINESTYLES[i % len(LINESTYLES)],
            markersize=3.2,
            markerfacecolor="white",
            markeredgewidth=1.4,
            linewidth=2.3,
            alpha=0.98,
            capsize=4 if yerr is not None else 0,
        )
    plt.xlabel("Malicious clients (%)")
    plt.ylabel(metric.upper() if len(metric) <= 3 else metric.title())
    plt.legend(frameon=True, framealpha=0.5)
    plt.xlim(summary["malicious_ratio"].min() * 100.0,summary["malicious_ratio"].max() * 100.0)
    savefig(out_dir / f"malicious_sensitivity_{metric}")


def plot_degradation(deg: pd.DataFrame, metric: str, out_dir: Path) -> None:
    deg_col = f"{metric}_degradation"
    plt.figure(figsize=(8.2, 5.3))
    for i, (label, g) in enumerate(deg.groupby("method_display", sort=False)):
        g = g.sort_values("malicious_ratio")
        plt.plot(
            g["malicious_ratio"] * 100.0,
            g[deg_col],
            label=label,
            marker=MARKERS[i % len(MARKERS)],
            # linestyle=LINESTYLES[i % len(LINESTYLES)],
            markersize=3.2,
            markerfacecolor="white",
            markeredgewidth=1.4,
            linewidth=2.3,
        )
    plt.axhline(0.0, linestyle="--", linewidth=1.6)
    plt.xlabel("Malicious clients (%)")
    if metric.lower() == "loss":
        plt.ylabel("Loss increase from 0% malicious")
    else:
        plt.ylabel(f"{metric.upper() if len(metric) <= 3 else metric.title()} drop from 0% malicious")
    plt.legend(frameon=True, framealpha=0.5)
    plt.xlim(deg["malicious_ratio"].min() * 100.0, deg["malicious_ratio"].max() * 100.0)
    savefig(out_dir / f"malicious_sensitivity_{metric}_degradation")


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot malicious sensitivity experiment.")
    parser.add_argument("--results_root", required=True)
    parser.add_argument("--out_dir", required=True)
    parser.add_argument("--metric", default="auc", help="acc, auc, f1, recall, precision, or loss")
    parser.add_argument("--paper", action="store_true")
    parser.add_argument("--font_size", type=int, default=24)
    args = parser.parse_args()

    set_plot_style(paper=args.paper, font_size=args.font_size)
    out_dir = Path(args.out_dir)
    csv_dir = out_dir / "csv"
    plot_dir = out_dir / "plots"
    csv_dir.mkdir(parents=True, exist_ok=True)
    plot_dir.mkdir(parents=True, exist_ok=True)

    df = load_all_metrics(args.results_root)
    df.to_csv(csv_dir / "merged_all_trials_metrics.csv", index=False)

    summary = final_metric_summary(df, args.metric)
    degradation = robustness_degradation(summary, args.metric)
    summary.to_csv(csv_dir / f"final_{args.metric}_by_malicious_ratio.csv", index=False)
    degradation.to_csv(csv_dir / f"{args.metric}_degradation_by_malicious_ratio.csv", index=False)

    plot_sensitivity(summary, args.metric, plot_dir)
    plot_degradation(degradation, args.metric, plot_dir)

    print("\nSaved malicious-sensitivity analysis")
    print(f"CSV outputs:  {csv_dir}")
    print(f"Plot outputs: {plot_dir}")
    print("\nSummary preview:")
    print(summary.to_string(index=False))


if __name__ == "__main__":
    main()
